function [tf, filtername] = readfilter2(filename, modulename, banks, ff, fs)
% function [tf, filtername] = readfilter2(filename, modulename, banks, ff, fs)
%
% This is a wrapper function for readfilters(file,module,banks)
% and returns the following:
%            tf: transfer function (note that the overall gain,
%                e.g. H1:LSC-DARM_GAIN, is not taken into account.
%    filtername: list of active filter banks specified by banks
%
% Input parameters:
%      filename: filter file generated by foton
%        module: name of the module, e.g. 'DARM'.
%         banks: array of active filter bank numbers, e.g. [0 3 4].
%            ff: frequency vector
%            fs: sampling frequency

[sos2,dgain2,filtername] = ...
    readfilters(filename, modulename, banks);
clear h2
for ii = 1:size(sos2,1),
    [b2,a2] = sos2tf(sos2(ii,:));
    h2(ii,:) = freqz(b2,a2,ff,fs);
end
hd2 = prod(h2,1);

tf = dgain2 * shiftdim(hd2,1);
return;